export default [
  {
    category: "News",
    color: "blue",
    items: {
      nyt: "https://nytimes.com",
      wapo: "https://washingtonpost.com",
      wsj: "https://wsj.com",
      reddit: "https://reddit.com/r/all",
      kagi: "https://kagi.com/",
    },
  },
  {
    category: "Social",
    color: "red",
    items: {
      gml: "https://mail.google.com/",
      yt: "https://youtube.com/",
      ig: "https://instagram.com",
      li: "https://linkedin.com",
      twi: "https://twitter.com",
      irc: "http://10.0.0.52:9001/",
    },
  },
  {
    category: "Finance",
    color: "green",
    items: {
      fin: "https://docs.google.com/spreadsheets/d/1T6EA-emeI0X3cjt0ahXD6BUWsGXk9S6N9_yqJ7kmW1w/edit#gid=0",
      rent: "https://property.onesite.realpage.com/welcomehome/home/login?siteId=2260960&CID=PAYMENTS-EMAIL&utm_source=Payments&utm_medium=email&utm_campaign=payments-email-CRR&utm_content=Encourage-electronic-payment#url=%23dashboard",
      wf: "https://wellsfargo.com",
      fid: "https://oltx.fidelity.com/ftgw/fbc/oftop/portfolio#summary",
      emp: "https://participant.empower-retirement.com/participant/#/login",
      citi: "https://www.citi.com/login",
      mstar: "https://www.morningstar.com/",
    },
  },
  {
    category: "Self Hosted",
    color: "purple",
    items: {
      ruTorrent: "http://10.0.0.52:8081/",
      calibre_w: "http://10.0.0.52:8083/",
      calibre: "http://10.0.0.52:8084/",
      readarr: "http://10.0.0.52:8787/",
      radarr: "http://10.0.0.52:7878/",
      sonarr: "http://10.0.0.52:8989/",
      sabnzbd: "http://10.0.0.52:8080/",
      nzbhydra: "http://10.0.0.52:5076/",
      tautulli: "http://10.0.0.52:8181/home",
      docker: "https://10.0.0.52:9443/#!/2/docker/containers",
      overseer: "https://bridgefour.uk",
    },
  },
];
